<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Swesim.Axis.Vapix</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>AxisVapix</AssemblyTitle>
    <Description>A .Net library for communicating with Axis network camera hardware</Description>
    <Company>Swesim</Company>
    <Product>AxisVapix</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.2</FileVersion>
    <InformationalVersion>1.0.1.0</InformationalVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>$(AssemblyVersion)</Version>
    <PackageProjectUrl>https://github.com/swesimse/axis-vapix-dotnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/swesimse/axis-vapix-dotnet</RepositoryUrl>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>